### ISSUE TITLE
Crash when running with Meta-2.gir

### ISSUE THREAD

**Issue by jantrushar** [gtkd-developers/gir-to-d#15]
Hello. Thank you for this library! 

I experienced a crash when running on Meta-2.gir (Mutter):
`girtod -i /usr/lib/mutter/Meta-2.gir -g /usr/lib/mutter/`

I tracked it down to file GirStruct.d line 740 because parentStruct is null and fixed this temporarily by adding right before: 
```
if ( !parentStruct )
    return false;
```
I did not track down the root cause yet.

Version: girtod 0.15.0+commit.11.gaa7149e (git clone from 8/8/2018)
Compiler: LDC - the LLVM D compiler (1.10.0)

Best Regards
Jan

**Comment by MikeWey** [comment]
I've added the check so it doesn't crash.

But to generate the correct code we probably need to recursively parse the includes.
The error occurs because we are looking for a parent defined in Gio, but `Mera-2.gir` doesn't list gio in the includes.
