### ISSUE TITLE
Option to rename types

### ISSUE THREAD

**Issue by dhasenan** [gtkd-developers/gir-to-d#22]
JavaScriptCore-4.0.gir defines a class named Exception. This is not allowed in D. In order for gir-to-d to wrap this library, we need a way to rename a type. The docs don't record a way to do this.

**Comment by dhasenan** [comment]
Functions too; `jsc_context_throw` is mapped to `void throw()`, which obviously doesn't work.

**Comment by dhasenan** [comment]
I *think* the `class` directive renames the generated class. There doesn't seem to be an equivalent for functions.

**Comment by dhasenan** [comment]
Oh, `move` takes three arguments: the thing to move, the thing to move it to, and the name to give it in that type.

**Comment by MikeWey** [comment]
For renaming functions you can use `alias`.

```
alias: throw throw_
```

`alias` also works on parameter names.
