### ISSUE TITLE
functions from handy/c/functions.d are "not defined" 

### ISSUE THREAD

**Issue by JeysonFlores** [gtkd-developers/gir-to-d#38]
Hi, I was testing the bindings for libhandy and I started getting some errors when the generated classes call the C-functions constructors. I imported `handy.c.functions` and called a simple function from it like this:
```D
import handy.c.functions;

void main()
{
	auto a = hdy_window_new();
}
```
and this fails due to this:
```bash
undefined reference to `hdy_window_new'
collect2: error: ld returned 1 exit status
```
It seems that for some reason it can't call the functions definied in the `c/functions.d` file. Do you know what is the problem? 
Thanks!

**Comment by MikeWey** [comment]
You will need to tell the linker you want to link with libhandy.

alternatively the binding can link with the library dynamically by passing the: `--use-runtime-linker` to gir-to-d when generating the binding.

**Comment by JeysonFlores** [comment]
Thanks!
