### ISSUE TITLE
gtkc backward compatibility change breaks other projects

### ISSUE THREAD

**Issue by ximion** [gtkd-developers/gir-to-d#4]
Hi!
Travis notified me that this change: https://github.com/gtkd-developers/gir-to-d/commit/21142a84f36e01196556406caad583b406cc753b breaks the appstream-generator project and possible others. Reason is that there simply is to "gtkc" package anywhere, yet, girtod inserts it into everything it processes.

What kind of problem was this patch trying to solve? (I can't see how applying it helps backwards compatibility...) In case the patch is necessary, can we maybe make it a config option somewhere, that you have to opt into?

**Comment by MikeWey** [comment]
I've put the changes behind an command line switch.

The changes were added to fix https://github.com/gnunn1/tilix/issues/938

**Comment by ximion** [comment]
Seems like https://github.com/gtkd-developers/GtkD/issues/200 should be fixed then... But anyway, having this change in a bugfix release was indeed surprising I guess...

In any case, thanks for fixing the issues so quickly! :-)
