### ISSUE TITLE
AssertError with JavaScriptCore-4.0.gir

### ISSUE THREAD

**Issue by dhasenan** [gtkd-developers/gir-to-d#9]
When trying to use gir-to-d to create bindings for libjavascriptcoregtk-4.0 (a part of WebKitGTK), I get an AssertError when trying to determine the library name:

```
core.exception.AssertError@/usr/include/dmd/phobos/std/regex/package.d(607): wrong match: 21..0
----------------
??:? _d_assert_msg [0x6dc576]
/usr/include/dmd/phobos/std/regex/package.d:608 inout pure nothrow @trusted inout(immutable(char)[]) std.regex.Captures!(immutable(char)[], ulong).Captures.opIndex!().opIndex(ulong) [0x6a46e2]
source/gtd/GirPackage.d:585 immutable(char)[] gtd.GirPackage.GirPackage.getDllNames() [0x6952a8]
source/gtd/GirPackage.d:539 immutable(char)[] gtd.GirPackage.GirPackage.getLibraries() [0x694f76]
source/gtd/GirPackage.d:510 void gtd.GirPackage.GirPackage.writeExternalFunctions() [0x694b44]
source/girtod.d:93 int girtod.main(immutable(char)[][]).__foreachbody3(ref gtd.GirPackage.GirPackage) [0x651792]
??:? _aaApply [0x6dda19]
source/girtod.d:85 _Dmain [0x6516aa]
```

The input gir file defines its shared library as `javascriptcoregtk-4.0` instead of the expected `libjavascriptcoregtk-4.0.so`. I don't know if this is incorrect or not, but that's in the gir file that comes with Ubuntu 16.04.

**Comment by MikeWey** [comment]
The expected shared library name would be `libjavascriptcoregtk-4-0.so.18` but the so version isn't in the gir files so i currently just add the `lib` and `.so`.

Loading the functions would fail on systems where the development libraries are installed separately, luckily the JavaScriptCore gir files don't contain any functions.
